### ISSUE TITLE
Проблема с индексами.

### ISSUE THREAD

**Issue by vpvpvpvp** [MechDevelopment/mrbeam#4]
![Screenshot from 2019-10-04 11-02-15](https://user-images.githubusercontent.com/55928886/66191246-90c7b200-e696-11e9-8ca6-4937a4ebc625.png)

Там какая-то проблема с индексами в циклах и сайт падает. Скорее всего let пропущено. Как временное решение можно просто закомментировал последние пару строк:

`export default function() {
  console.log("Finite Elements");
}`

**Comment by divasilevski** [comment]
Я когда запулил, у меня синтаксическая ошибка была на этом месте. Я тоже просто коммент поставил.

**Comment by vpvpvpvp** [comment]
#
